# -*- coding: utf-8 -*-
"""linearRegression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sTuOLk-TICa54pKZBewSesQyebXWlW2T

Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""Importing the data"""

data_set = pd.read_csv("Salary_Data.csv")
x = data_set.iloc[:,:-1].values
y = data_set.iloc[:,-1].values
print(x)
print(y)

"""Splitting the dataset"""

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=0)
print(x_train)
print(y_train)

"""Training the sample linear regressoion on the training set"""

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

"""Predicting the test set results """

y_pred = regressor.predict(x_test)

"""Visualising the training set results """

plt.scatter(x_train, y_train, color='red')
plt.plot(x_train, regressor.predict(x_train),color='blue')
plt.title('salary vs experience(training set)')
plt.xlabel('years of experience')
plt.ylabel('salary')
plt.show()

"""Visualising the test set results """

plt.scatter(x_test, y_test, color='red')
plt.plot(x_test, regressor.predict(x_test),color='blue')
plt.title('salary vs experience(training set)')
plt.xlabel('years of experience')
plt.ylabel('salary')
plt.show()